// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4jVAO-UwDnrLMB4MjS21J9R8wmG4bm4',
    appId: '1:176034778877:web:508c825db61d3375147894',
    messagingSenderId: '176034778877',
    projectId: 'try-oauth-73caf',
    authDomain: 'try-oauth-73caf.firebaseapp.com',
    storageBucket: 'try-oauth-73caf.firebasestorage.app',
    measurementId: 'G-YK4K900XWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA94EcGVsFIzsVlAfwbZuEsH-QC0cAs-d8',
    appId: '1:176034778877:android:bd5946f1509a80bd147894',
    messagingSenderId: '176034778877',
    projectId: 'try-oauth-73caf',
    storageBucket: 'try-oauth-73caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__sSomMHcCa7DLU0YZNrcHypnDtTys9U',
    appId: '1:176034778877:ios:a2278ef4a0d628fe147894',
    messagingSenderId: '176034778877',
    projectId: 'try-oauth-73caf',
    storageBucket: 'try-oauth-73caf.firebasestorage.app',
    iosClientId: '176034778877-avtr2c5ssvua163vl371lfmjdjtgm7hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rextraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__sSomMHcCa7DLU0YZNrcHypnDtTys9U',
    appId: '1:176034778877:ios:a2278ef4a0d628fe147894',
    messagingSenderId: '176034778877',
    projectId: 'try-oauth-73caf',
    storageBucket: 'try-oauth-73caf.firebasestorage.app',
    iosClientId: '176034778877-avtr2c5ssvua163vl371lfmjdjtgm7hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rextraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ4jVAO-UwDnrLMB4MjS21J9R8wmG4bm4',
    appId: '1:176034778877:web:cf5a90c069460aff147894',
    messagingSenderId: '176034778877',
    projectId: 'try-oauth-73caf',
    authDomain: 'try-oauth-73caf.firebaseapp.com',
    storageBucket: 'try-oauth-73caf.firebasestorage.app',
    measurementId: 'G-3NHCVWNSSK',
  );
}
